### ISSUE TITLE
Parser fails on results with only citation: TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by tengerye** [ckreibich/scholar.py#118]
Hi, the following command `scholar.py -a "albert einstein" -t -s "quantum theory,"` will cause the following error:
```
Traceback (most recent call last):
  File "scholar.py", line 1310, in <module>
    sys.exit(main())
  File "scholar.py", line 1293, in main
    querier.send_query(query)
  File "scholar.py", line 1027, in send_query
    self.parse(html)
  File "scholar.py", line 1055, in parse
    parser.parse(html)
  File "scholar.py", line 397, in parse
    self._parse_article(div)
  File "scholar.py", line 571, in _parse_article
    if tag.find('div', {'class': 'gs_ttss'}):
TypeError: slice indices must be integers or None or have an __index__ method
```

I checked the html returned and it shows like this:
![screenshot from 2019-02-08 16-07-54](https://user-images.githubusercontent.com/15181821/52466011-c2e24c00-2bbb-11e9-89d7-f9a7bf17604e.png)

Would you please have a look?

**Comment by GianniSalami** [comment]
I have noticed that too. From what I found the gs_ttss class does not exist on the google scholar search results page. If anyone knows how to fix it that would be awesome

**Comment by vict0rsch** [comment]
Having this issue here too

**Comment by simplecomplex-tech** [comment]
Having same issue too

**Comment by simplecomplex-tech** [comment]
follow this one:  https://github.com/ckreibich/scholar.py/issues/116
