### ISSUE TITLE
scholar.py not working at all, always TypeError happens

### ISSUE THREAD

**Issue by Bonesovich** [ckreibich/scholar.py#39]
I always get this error when trying to run scholar.py:

C:\>python scholar.py --phrase "quantum" -c 1
Traceback (most recent call last):
  File "scholar.py", line 1272, in <module>
    sys.exit(main())
  File "scholar.py", line 1255, in main
    querier.send_query(query)
  File "scholar.py", line 983, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "scholar.py", line 823, in get_url
    urlargs[key] = quote(encode(val))
  File "C:\Python34\lib\urllib\parse.py", line 694, in quote
    return quote_from_bytes(string, safe)
  File "C:\Python34\lib\urllib\parse.py", line 719, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

No matter what parameters I put in it does not work at all. Im running it under Win 7 with Python v 3.4.2.

**Comment by ckreibich** [comment]
This should now be fixed thanks to https://github.com/ckreibich/scholar.py/commit/b6d92fa8e1472e63b79dd019bd9cca0cad3569d4 — please try again and let me know if you still have problems.

**Comment by Celestina013ss** [comment]
I get scholar is not recognized as internal or external command, operable program or batch file?
